# Generated by Django 5.2.15 on 2026-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_created_at_item_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
